sudo: required

language: go
go: "1.11.5"

services:
  - docker

before_install:
  - sudo apt-get install -y apt-transport-https ca-certificates software-properties-common zip python3-pip python3-dev build-essential
  - sudo pip3 install --upgrade pip
  - pip3 install --upgrade awscli --user

jobs:
  include:
    - stage: files
      script: make test-license
      name: "License headers"
    - stage: tests
      script: make test-go
      name: "Go tests"
    - stage: release
      if: branch = master OR branch =~ /^[0-9]\.[0-9]$/
      script: make test-version
      name: "Check version header"
      script: make tf-images
      name: "Tensorflow"
      script: make spark-images && make test-python
      name: "Spark and test python"
      script: make argo-images
      name: "Argo"
      script: make operator-images
      name: "Operator"
    - stage: deploy
      if: branch = master OR branch =~ /^[0-9]\.[0-9]$/
      script: make build-and-upload
    

