sudo: required

language: go
go: "1.11.5"

services:
  - docker

before_install:
  - sudo apt-get install -y apt-transport-https ca-certificates software-properties-common zip python3-pip python3-dev build-essential
  - sudo pip3 install --upgrade pip
  - pip3 install --upgrade awscli --user

jobs:
  include:
    - stage: Images and Tests
      script: make tf-images
      name: "Tensorflow"
    - script: make spark-images && make test-python
      name: "Spark and test python"
    - script: make argo-images
      name: "Argo"
    - script: make operator-images
      name: "Operator"
    - script: make test-go
      name: "Go tests"
    - stage: deploy
      if: branch = master
      script: build-and-upload
      


